# reference: https://verdantfox.com/blog/view/how-to-use-git-pre-commit-hooks-the-hard-way-and-the-easy-way
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
        args:
          - --unsafe
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
  - repo: https://github.com/nix-community/nixpkgs-fmt
    rev: v1.3.0
    hooks:
      - id: nixpkgs-fmt
  - repo: local
    hooks:
      - id: statix
        name: statix-lint
        entry: statix fix --ignore "templates/" .
        language: system
        types: [nix]
  - repo: local
    hooks:
      - id: deadnix
        name: deadnix-lint
        entry: deadnix --edit --exclude "templates/" .
        language: system
        types: [nix]
  # - repo: local
  #   hooks:
  #     - id: markdown-lint
  #       name: markdown-lint
  #       entry: npm run markdown-lint
  #       language: markdown
  #       types: [md]
